name: Pet Store App CI/CD to Azure App Service
  
env:
  AZURE_CONTAINER_REGISTRY: azurequarkus.azurecr.io
  AZURE_CONTAINER_REGISTRY_USERNAME: azurequarkuscr
  
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      name: Building Azure Quarkus App with Java 11
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run Maven build
      run: mvn -f pom.xml --batch-mode --update-snapshots verify
    - uses: azure/docker-login@v1
      name: Build Docker image
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZUREQUARKUSCRSECRET }}
    - name: Push Docker image to Azure Container Registry    
      run: |
        docker build petstore/petstoreapp -t ${{env.AZURE_CONTAINER_REGISTRY}}/petstoreapp:latest -t ${{ env.AZURE_CONTAINER_REGISTRY }}/petstoreapp:${{ github.sha }}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/petstoreapp:${{ github.sha }}
        docker push  ${{ env.AZURE_CONTAINER_REGISTRY }}/petstoreapp:latest
